tags: 
  name: hello word
  description: the first API

paths:
  /api/examples/HelloWord:
    get:
      summary: return this Hello Word
      tags: [hello word]
      responses: 
        200:
          description: 'OK'
          content:
            application/json:
              schema: 
                type: object
                properties:
                  message: 
                    type: string
                    example: "Helloword"